micronaut:
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: vfdvnhvbbhjfsvrbjdlhfvszdljkbhngsvdfjk;bnawdawsegfaedrgsrtd

datasources:
  default:
    url: ${JDBC_URL}
    username: social_media
    password: social_media
    driverClassName: org.postgresql.Driver
    minPoolSize: 5
    maxPoolSize: 100